version: '3'


services:

  app:

    build:
      context: .
      dockerfile: Dockerfile


    volumes:
      - .:/app/
      - /app/node_modules

    container_name: nest-app
    ports:
      - ${PORT}:${PORT}
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      PORT: ${PORT}
      HOST_API: ${HOST_API}
      FRONTEND_ORIGIN: ${FRONTEND_ORIGIN}
      CRORS_METHODS: ${CRORS_METHODS}


  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: ${DB_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data


volumes:
  postgres-db:
    external: false