export enum DatabaseType {
  MySQL = "mysql",
  MariaDB = "mariadb",
  Postgres = "postgres",
  CockroachDB = "cockroachdb",
  SQLite = "sqlite",
  MSSQL = "mssql",
  SAP = "sap",
  Oracle = "oracle",
  Cordova = "cordova",
  NativeScript = "nativescript",
  ReactNative = "react-native",
  SQLJS = "sqljs",
  MongoDB = "mongodb",
  AuroraMySQL = "aurora-mysql",
  AuroraPostgres = "aurora-postgres",
  Expo = "expo",
  BetterSQLite3 = "better-sqlite3",
  Capacitor = "capacitor",
  Spanner = "spanner"
}
